# Étape 1: Utilisation de Node.js pour builder l'application Angular
FROM node:16 AS build

# Définir le répertoire de travail dans le dossier src
WORKDIR /app

# Copier le package.json et installer les dépendances
COPY src/package*.json ./
RUN npm install

# Copier le reste des fichiers du projet Angular depuis src
COPY src/ ./

# Construire l'application Angular (mode production)
RUN npm run build --prod

# Étape 2: Utilisation de Nginx pour servir l'application Angular
FROM nginx:alpine

# Copier les fichiers buildés de l'étape précédente dans le dossier Nginx
COPY --from=build /app/dist/your-angular-app /usr/share/nginx/html

# Exposer le port 80 (par défaut pour Nginx)
EXPOSE 80

# Commande de démarrage de Nginx
CMD ["nginx", "-g", "daemon off;"]
