# Étape 1: Utilisation de Node.js pour builder l'application Angular
FROM node:16 AS build

WORKDIR /app

# Copier le package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste des fichiers du projet Angular
COPY . .

# Construire l'application Angular (mode production)
RUN npm run build --prod

# Étape 2: Utilisation de Nginx pour servir l'application
FROM nginx:alpine
COPY --from=build /app/dist/your-angular-app /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]